# Generated by Django 4.2.7 on 2024-02-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_word', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('domain', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('remote_id', models.CharField(max_length=55, unique=True)),
                ('founded_at', models.DateTimeField()),
                ('parsed_at', models.DateTimeField()),
            ],
        ),
    ]
