# Generated by Django 5.0.1 on 2024-02-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('1', 'keys_so_parsing')], default='1', max_length=55)),
                ('job_data', models.JSONField(null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('last_exec_time', models.DateTimeField()),
            ],
        ),
    ]
