# Generated by Django 5.0.1 on 2024-02-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_cronjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='last_exec_time',
            field=models.DateTimeField(null=True),
        ),
    ]
